### ISSUE TITLE
TypeError: Cannot read property 'event' of undefined

### ISSUE THREAD

**Issue by DODMax** [drobee/nova-sluggable#6] opened 2019-05-14 07:36 UTC
Getting the following error since I updated from 1.1.1 to 1.1.2.
![image](https://user-images.githubusercontent.com/1137276/57679475-9ecc5600-7655-11e9-82b9-454e0830df73.png)

Cheers!

**Comment by drobee** [comment] 2019-05-23 20:12
@DODMax i can't reproduce this. Can you help me by pasting your `Slug` field implementation from your resource?

**Comment by aihowes** [comment] 2019-06-06 08:49
Had the same issue, I believe this is because unless you use any of the functions that call `setOption()` the component is never never recieving the `options` array.

@DODMax a quick fix for this would be to use use the Slug field like so `Slug::make('Slug')->withMeta(['options' => ['event' => 'keyup']])`

@drobee I think if you implement a `jsonSerialize` function and merge options with the parent's `jsonSerialize`

**Closed as completed** 2019-07-21 18:33 UTC

**Comment by drobee** [comment] 2019-07-21 18:40
Thank you, @aihowes! However i found a better solution. It's fixed now in the latest release.
